[package]
name = "op_application"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
op_engine = { path = "../op_engine"}
repl-rs = "0.2.7"
